language: node_js
node_js:
  - 12
instal:
  - yarn install
script:
  - npm run build
branches:
  only:
    - master
    - dev
deploy:
  provider: pages
  verbose: true
  github-token: $GITHUB_TOKEN # github 上的token环境变量
  on:
    branch: dev

